# Generated by Django 3.2.9 on 2021-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('specie', models.CharField(max_length=45, verbose_name='specie')),
                ('breed', models.CharField(max_length=45, null=True, verbose_name='breed')),
                ('gender', models.CharField(max_length=45, verbose_name='gender')),
                ('bday_aprox', models.DateField(verbose_name='bday_aprox')),
                ('date_register', models.DateField(verbose_name='date_register')),
                ('avaliable', models.BooleanField(default=True, verbose_name='avaliable')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('image', models.CharField(max_length=250, null=True, verbose_name='image')),
                ('user', models.IntegerField(verbose_name='user')),
            ],
        ),
    ]
